@HOST = http://localhost:8080

POST {{HOST}}/login HTTP/1.1
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjliZjUyZTlmLTM2MzQtNDA3Ny1iNjdmLWZkOWE5NzQ1ZWQ0ZiIsIm5hbWUiOiJ2aW5uaWUiLCJlbWFpbCI6InZpbm5pZUBtYXJ0aW5zLmNvbSIsInByb2ZpbGUiOiJSRUNSVUlURVIiLCJjb21wYW55IjoiZXN0cmVsYSIsImlhdCI6MTY4NDI0ODYyMSwiZXhwIjoxNjg0MjY2NjIxfQ.4SXCIY98EZPw17q482fY7zQBpF5zkEVds7A51cEKSBI

{
  "email": "agoravaiMESMO2@martins.com",
  "password": "1234"
}